name: Trigger auto deployment for beseo-conapps01

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '/app/**'
    - '.github/workflows/beseo-conapps01-AutoDeployTrigger-2beb1efd-f065-4bf6-a8cd-2a66cec36720.yml'

  # Allow mannually trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.BESEOCONAPPS01_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }}/app 
          registryUrl: beseoacr01.azurecr.io
          registryUsername: ${{ secrets.BESEOCONAPPS01_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.BESEOCONAPPS01_REGISTRY_PASSWORD }}
          containerAppName: beseo-conapps01
          resourceGroup: az-acr-rg
          imageToBuild: beseoacr01.azurecr.io/beseo-conapps01:${{ github.sha }}
          dockerfilePath: Dockerfile

     

